### ISSUE TITLE
deprecated usage of set-output is being removed

### ISSUE THREAD

**Issue by mikehaas763** [rickstaa/action-get-semver#18]
Looks like this action will stop working soon. I think the new way to do it is to output to $GITHUB_OUTPUT, but that maybe depends on how set-output is being used in the first place.

> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

**Comment by rickstaa** [comment]
@mikehaas763 Thanks for the update. Fixed in https://github.com/rickstaa/action-get-semver/releases/tag/v1.4.0.
